name: "bclconvert"
description: Demultiplex Illumina BCL files
keywords:
  - demultiplex
tools:
  - "bclconvert":
      description: "Demultiplex Illumina BCL files"
      homepage: "https://support.illumina.com/sequencing/sequencing_software/bcl-convert.html"
      documentation: "https://support-docs.illumina.com/SW/BCL_Convert/Content/SW/FrontPages/BCL_Convert.htm"
      tool_dev_url: "NA"
      doi: "NA"
      licence: "NA"

input:
  - samplesheet:
      type: file
      description: "Input samplesheet"
      pattern: "*.{csv}"
  - run_dir:
      type: directory
      description: "Input run directory"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - fastq:
      type: file
      description: Demultiplexed FASTQ files
      pattern: "*.{fastq.gz}"
  - reports:
      type: file
      description: Demultiplexing Reports
      pattern: "Reports/*.{csv,xml}"
  - logs:
      type: file
      description: Log files
      pattern: "Logs/*.{log,txt}"
  - interop:
      type: file
      description: Interop files
      pattern: "Interop/*.{bin}"
authors:
  - "@matthdsm"
